services:
  stats-db:
    image: postgres:16.1-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stats"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - stats_data:/var/lib/postgresql/data
      - ./stats-service/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  stats-server:
    build:
      context: ./stats-service
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  ewm-db:
    image: postgres:16.1-alpine
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ewm"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ewm_data:/var/lib/postgresql/data

  ewm-service:
    build: ./main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

volumes:
  stats_data:
  ewm_data: